#python program to demonstrate string functions
s=input("enter the sentence badiger")
s1=s.strip()
print(f"after removing leading and traling spaces\n{s1}")
s2=s1.upper()
print(f"after converting to uppercase\n{s2}")
s3=s1.replace(',',' ')
print(f"after replacing comma with spaces\n{s3}")
slst=s3.split(' ')
print("after spliting the string into list")
print(slst)
word=input("enter the word you want to count")
c=s3.count(word)
print(f"the word {word} has appeared {c} times in the string")